apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-mongo
spec:
  rules:
  - host: "adminmongo.realworld.local.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: admin-mongo
            port:
              number: 8082